using System;
using System.Collections.Generic;
using System.Text;

namespace LithUSS
{
    public enum ErrorEnum
    {
        NO_ERR = 0,

        //TextNormalization klaidu kodai
        ERROR_TEXTNORMALIZATION_OPENING_RULES_FILE = -20,
        ERROR_TEXTNORMALIZATION_OPENING_FILE_SPECIFIED_IN_RULES_FILE = -21,

        ERROR_TEXTNORMALIZATION_BUFFER_OVERFLOW = -22,

        //TranscrLUSS klaidu kodai
        ERROR_TRANSCRLUSS_OPENING_TRANSCR_RULES_FILE = -35,
        ERROR_TRANSCRLUSS_READING_TRANSCR_RULES_FILE = -36,

        //UnitSelection klaidu kodai
        ERROR_UNITSELECTION_OPENING_SETTINGS_FILE = -40,
        ERROR_UNITSELECTION_READING_SETTINGS_FILE = -41,
        ERROR_UNITSELECTION_OPENING_JOINING_COSTS_FILE = -42,
        ERROR_UNITSELECTION_READING_JOINING_COSTS_FILE = -43,
        ERROR_UNITSELECTION_OPENING_LEFT_SUBSTITUTION_COSTS_FILE = -44,
        ERROR_UNITSELECTION_READING_LEFT_SUBSTITUTION_COSTS_FILE = -45,
        ERROR_UNITSELECTION_OPENING_RIGHT_SUBSTITUTION_COSTS_FILE = -46,
        ERROR_UNITSELECTION_READING_RIGHT_SUBSTITUTION_COSTS_FILE = -47,
        ERROR_UNITSELECTION_OPENING_DB_FON_FILE = -48,
        ERROR_UNITSELECTION_DB_FON_EXCEEDED_MAX_UNITS = -49,
        ERROR_UNITSELECTION_READING_DB_FON_FILE = -50,
        ERROR_UNITSELECTION_OPENING_DB_FON_WEIGHTS_FILE = -51,
        ERROR_UNITSELECTION_READING_DB_FON_WEIGHTS_FILE = -52,

        ERROR_UNITSELECTION_MEMORY_ALLOCATION = -53,
        ERROR_UNITSELECTION_UNIT_NOT_FOUND = -54,
        ERROR_UNITSELECTION_UNEXPECTED_1 = -55,
        ERROR_UNITSELECTION_UNEXPECTED_2 = -56,
        ERROR_UNITSELECTION_UNEXPECTED_3 = -57,
        ERROR_UNITSELECTION_UNEXPECTED_4 = -58,

        //RateChange klaidu kodai
        ERROR_RATECHANGE_OPENING_DB_FILE = -60,
        ERROR_RATECHANGE_DETECTING_DB_FILE_SIZE = -61,
        ERROR_RATECHANGE_UNEVEN_DB_FILE_SIZE = -62,
        ERROR_RATECHANGE_MEMORY_ALLOCATION_FOR_DB = -63,
        ERROR_RATECHANGE_READING_DB_FILE = -64,
        ERROR_RATECHANGE_UNFINISHED_READING_DB_FILE = -65,
        ERROR_RATECHANGE_OPENING_DB_FON_WEIGHTS_FILE = -66,
        ERROR_RATECHANGE_DETECTING_DB_FON_WEIGHTS_FILE_SIZE = -67,
        ERROR_RATECHANGE_READING_DB_FON_WEIGHTS_FILE = -68,
        ERROR_RATECHANGE_UNFINISHED_READING_DB_FON_WEIGHTS_FILE = -69,
        ERROR_RATECHANGE_MEMORY_ALLOCATION_FOR_PHONEME_LIST = -70,
        ERROR_RATECHANGE_UNSPECIFIED_PHONEME_LENGTH = -71,
        ERROR_RATECHANGE_NONNUMERICAL_PHONEME_LENGTH = -72,
        ERROR_RATECHANGE_OPENING_DB_PIK_FILE = -73,
        ERROR_RATECHANGE_DETECTING_DB_PIK_FILE_SIZE = -74,
        ERROR_RATECHANGE_READING_DB_PIK_FILE = -75,
        ERROR_RATECHANGE_UNFINISHED_READING_DB_PIK_FILE = -76,
        ERROR_RATECHANGE_MEMORY_ALLOCATION_FOR_PIK_LIST = -77,
        ERROR_RATECHANGE_NONNUMERICAL_PIK_VALUE = -78,
        ERROR_RATECHANGE_MEMORY_ALLOCATION_FOR_PIK_INFO = -79,

        ERROR_RATECHANGE_MEMORY_ALLOCATION_FOR_CHANGED_RATE_DB = -80,
        ERROR_RATECHANGE_SIGNAL_BUFFER_OVERFLOW = -81,

        //LithUSS klaidu kodai
        ERROR_LITHUSS_LOADING_TEXTNORMALIZATION_DLL = -19,
        ERROR_LITHUSS_LOADING_TRANSCRLUSS_DLL = -34,
        ERROR_LITHUSS_OPENING_FACTORS_FILE = -37,
        ERROR_LITHUSS_READING_FACTORS_FILE = -38,
        ERROR_LITHUSS_LOADING_UNITSELECTION_DLL = -39,
        ERROR_LITHUSS_LOADING_RATECHANGE_DLL = -59,

        ERROR_LITHUSS_MEMORY_ALLOCATION = -15,
        ERROR_LITHUSS_MEMORY_REALLOCATION = -16,
        ERROR_LITHUSS_EVENTS_ARRAY_OVERFLOW = -17,
    }
}
